version: '3.7'

services:
  gitlab:
    image: 'seu-usuario/gitlab-custom:latest'
    container_name: gitlab
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

  gitlab-runner:
    image: 'seu-usuario/gitlab-runner-custom:latest'
    container_name: gitlab-runner
    restart: always
    volumes:
      - './gitlab/gitlab-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network
    depends_on:
      - gitlab

networks:
  gitlab-network:
    name: gitlab-network